---
http_interactions:
- request:
    method: get
    uri: http://localhost:8111/guestAuth/app/rest/buildTypes/id:BuildTypeTests_GetBuildTypeConfigTests/artifact-dependencies
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - TeamCity Ruby Client 0.4.0
      Accept:
      - application/json; charset=utf-8
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Set-Cookie:
      - RememberMe=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
      - TCSESSIONID=B085BECD7F8651487AD253C6E17EE06A; Path=/; HttpOnly
      Pragma:
      - no-cache
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Cache-Control:
      - no-cache
      - no-store
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Date:
      - Wed, 14 Aug 2013 11:47:25 GMT
    body:
      encoding: US-ASCII
      string: ! '{"artifact-dependency":[{"id":"0","type":"artifact_dependency","properties":{"property":[{"name":"cleanDestinationDirectory","value":"false"},{"name":"pathRules","value":"version.txt"},{"name":"revisionName","value":"lastSuccessful"},{"name":"revisionValue","value":"latest.lastSuccessful"}]},"source-buildType":{"id":"BuildTypeTests_BuildTypeWithNoTemplate","name":"BuildTypeWithNoTemplate","href":"/guestAuth/app/rest/buildTypes/id:BuildTypeTests_BuildTypeWithNoTemplate","projectName":"BuildTypeTests","projectId":"BuildTypeTests","webUrl":"http://localhost:8111/viewType.html?buildTypeId=BuildTypeTests_BuildTypeWithNoTemplate"}}]}'
    http_version: 
  recorded_at: Wed, 14 Aug 2013 11:47:25 GMT
recorded_with: VCR 2.4.0
