---
http_interactions:
- request:
    method: get
    uri: http://localhost:8111/guestAuth/app/rest/buildTypes/id:BuildTypeTests_GetBuildTypeConfigTests/parameters
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - TeamCity Ruby Client 0.4.0
      Accept:
      - application/json; charset=utf-8
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Set-Cookie:
      - RememberMe=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
      - TCSESSIONID=AA49EB46FE24CBB09216077FA2D4FC94; Path=/; HttpOnly
      Pragma:
      - no-cache
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Cache-Control:
      - no-cache
      - no-store
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Date:
      - Wed, 14 Aug 2013 11:23:54 GMT
    body:
      encoding: US-ASCII
      string: ! '{"property":[{"name":"GetTestParam","value":"1"}]}'
    http_version: 
  recorded_at: Wed, 14 Aug 2013 11:23:55 GMT
recorded_with: VCR 2.4.0
